### Obtener todos los perros
GET http://localhost:3000/api/perros

### Obtener un perro por ID
GET http://localhost:3000/api/perros/68560a2d08080f82ede5276

### Agregar un nuevo perro
POST http://localhost:3000/api/perros
Content-Type: application/json

{
  "name": "Fido",
  "breed": "Golden Retriever",
  "age": 2,
  "isGoodBoy": true
}

### Actualizar un perro
PUT http://localhost:3000/api/perros/6856202f613b21884866af10
Content-Type: application/json

{
  "name": "Fido El Magnifico",
  "age": 4,
  "isGoodBoy": false
}

### Eliminar un perro
DELETE http://localhost:3000/api/perros/68588cf8c07ca023b1a69e12

